### ISSUE TITLE
Recording Video on OnePlus Camera 

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/proprietary_vendor_oneplus-guacamole#1]
Does it work for you?
I can't figure out how to fix on hotdog

**Comment by gwolf2u** [comment]
is working fine with sideloaded OP Cam v3.3.8

**Comment by ShevT** [comment]
Those, is this camera not working for You? 
https://gitlab.com/crdroidandroid/android_vendor_oneplus_apps/-/tree/12.0/guacamole/proprietary/system_ext/priv-app/OnePlusCamera

**Comment by ShevT** [comment]
What repository are You using?

**Comment by gwolf2u** [comment]
Not using prebuilt
Sideloading
Yet to consider if I want to bundle it or not
